function packageToolbox(releaseType, versionString)
    arguments
        releaseType {mustBeTextScalar,mustBeMember(releaseType,["build","major","minor","patch","specific"])} = "build"
        versionString {mustBeTextScalar} = "";
    end
    installMatBox()
    projectRootDir = ommtools.projectdir();
    addpath(genpath(projectRootDir))
    pathFolderList = getPathFolderList();
    matbox.tasks.packageToolbox(projectRootDir, releaseType, versionString, 'PathFolders', pathFolderList)
end

function pathFolderList = getPathFolderList()

    pathFolderList = [...
        fullfile("code", "internal"), ...
        fullfile("code", "internal", "property_validation"), ...
        fullfile("code", "livescripts"), ...
        fullfile("code", "schemas", "latest"), ...
        fullfile("code", "mixedtypes", "latest"), ...
        fullfile("code", "enumerations", "latest") ...
        ];
end
